using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IBSANBR.Models
{
    public class ElementoNacional
    {
        public int Id { get; set; }
        public string Competencia { get; set; }
        public decimal IN002 { get; set; }
        public decimal IN003 { get; set; }
        public decimal IN004 { get; set; }
        public decimal IN005 { get; set; }
        public decimal IN006 { get; set; }
        public decimal IN007 { get; set; }
        public decimal IN008 { get; set; }
        public decimal IN012 { get; set; }
        public decimal IN018 { get; set; }
        public decimal IN019 { get; set; }
        public decimal IN026 { get; set; }
        public decimal IN027 { get; set; }
        public decimal IN029 { get; set; }
        public decimal IN030 { get; set; }
        public decimal IN031 { get; set; }
        public decimal IN032 { get; set; }
        public decimal IN033 { get; set; }
        public decimal IN034 { get; set; }
        public decimal IN035 { get; set; }
        public decimal IN036 { get; set; }
        public decimal IN037 { get; set; }
        public decimal IN038 { get; set; }
        public decimal IN039 { get; set; }
        public decimal IN040 { get; set; }
        public decimal IN041 { get; set; }
        public decimal IN042 { get; set; }
        public decimal IN045 { get; set; }
        public decimal IN048 { get; set; }
        public decimal IN054 { get; set; }
        public decimal IN060 { get; set; }
        public decimal IN101 { get; set; }
        public decimal IN102 { get; set; }
        public decimal IN001 { get; set; }
        public decimal IN009 { get; set; }
        public decimal IN010 { get; set; }
        public decimal IN011 { get; set; }
        public decimal IN013 { get; set; }
        public decimal IN014 { get; set; }
        public decimal IN017 { get; set; }
        public decimal IN020 { get; set; }
        public decimal IN022 { get; set; }
        public decimal IN023 { get; set; }
        public decimal IN025 { get; set; }
        public decimal IN028 { get; set; }
        public decimal IN043 { get; set; }
        public decimal IN044 { get; set; }
        public decimal IN049 { get; set; }
        public decimal IN050 { get; set; }
        public decimal IN051 { get; set; }
        public decimal IN052 { get; set; }
        public decimal IN053 { get; set; }
        public decimal IN055 { get; set; }
        public decimal IN057 { get; set; }
        public decimal IN058 { get; set; }
        public decimal IN015 { get; set; }
        public decimal IN016 { get; set; }
        public decimal IN021 { get; set; }
        public decimal IN024 { get; set; }
        public decimal IN046 { get; set; }
        public decimal IN047 { get; set; }
        public decimal IN056 { get; set; }
        public decimal IN059 { get; set; }
        public decimal IN071 { get; set; }
        public decimal IN072 { get; set; }
        public decimal IN073 { get; set; }
        public decimal IN074 { get; set; }
        public decimal IN075 { get; set; }
        public decimal IN076 { get; set; }
        public decimal IN077 { get; set; }
        public decimal IN079 { get; set; }
        public decimal IN080 { get; set; }
        public decimal IN082 { get; set; }
        public decimal IN083 { get; set; }
        public decimal IN084 { get; set; }
        public decimal IN085 { get; set; }
        public decimal FN001 { get; set; }
        public decimal FN002 { get; set; }
        public decimal FN003 { get; set; }
        public decimal FN004 { get; set; }
        public decimal FN005 { get; set; }
        public decimal FN006 { get; set; }
        public decimal FN007 { get; set; }
        public decimal FN008 { get; set; }
        public decimal FN010 { get; set; }
        public decimal FN011 { get; set; }
        public decimal FN013 { get; set; }
        public decimal FN014 { get; set; }
        public decimal FN015 { get; set; }
        public decimal FN016 { get; set; }
        public decimal FN017 { get; set; }
        public decimal FN018 { get; set; }
        public decimal FN019 { get; set; }
        public decimal FN020 { get; set; }
        public decimal FN021 { get; set; }
        public decimal FN022 { get; set; }
        public decimal FN023 { get; set; }
        public decimal FN024 { get; set; }
        public decimal FN025 { get; set; }
        public decimal FN026 { get; set; }
        public decimal FN027 { get; set; }
        public decimal FN028 { get; set; }
        public decimal FN030 { get; set; }
        public decimal FN031 { get; set; }
        public decimal FN032 { get; set; }
        public decimal FN033 { get; set; }
        public decimal FN034 { get; set; }
        public decimal FN035 { get; set; }
        public decimal FN036 { get; set; }
        public decimal FN037 { get; set; }
        public decimal FN038 { get; set; }
        public decimal FN039 { get; set; }
        public decimal FN041 { get; set; }
        public decimal FN042 { get; set; }
        public decimal FN043 { get; set; }
        public decimal FN044 { get; set; }
        public decimal FN045 { get; set; }
        public decimal FN046 { get; set; }
        public decimal FN047 { get; set; }
        public decimal FN048 { get; set; }
        public decimal FN051 { get; set; }
        public decimal FN052 { get; set; }
        public decimal FN053 { get; set; }
        public decimal FN054 { get; set; }
        public decimal FN055 { get; set; }
        public decimal FN056 { get; set; }
        public decimal FN057 { get; set; }
        public decimal FN058 { get; set; }
        public decimal AG001 { get; set; }
        public decimal AG002 { get; set; }
        public decimal AG003 { get; set; }
        public decimal AG004 { get; set; }
        public decimal AG005 { get; set; }
        public decimal AG006 { get; set; }
        public decimal AG007 { get; set; }
        public decimal AG008 { get; set; }
        public decimal AG010 { get; set; }
        public decimal AG011 { get; set; }
        public decimal AG012 { get; set; }
        public decimal AG013 { get; set; }
        public decimal AG014 { get; set; }
        public decimal AG015 { get; set; }
        public decimal AG017 { get; set; }
        public decimal AG018 { get; set; }
        public decimal AG019 { get; set; }
        public decimal AG020 { get; set; }
        public decimal AG021 { get; set; }
        public decimal AG022 { get; set; }
        public decimal AG024 { get; set; }
        public decimal AG026 { get; set; }
        public decimal AG027 { get; set; }
        public decimal AG028 { get; set; }
        public decimal ES001 { get; set; }
        public decimal ES002 { get; set; }
        public decimal ES003 { get; set; }
        public decimal ES004 { get; set; }
        public decimal ES005 { get; set; }
        public decimal ES006 { get; set; }
        public decimal ES007 { get; set; }
        public decimal ES008 { get; set; }
        public decimal ES009 { get; set; }
        public decimal ES012 { get; set; }
        public decimal ES013 { get; set; }
        public decimal ES014 { get; set; }
        public decimal ES015 { get; set; }
        public decimal ES026 { get; set; }
        public decimal ES028 { get; set; }
        public decimal QD001 { get; set; }
        public decimal QD002 { get; set; }
        public decimal QD003 { get; set; }
        public decimal QD004 { get; set; }
        public decimal QD006 { get; set; }
        public decimal QD007 { get; set; }
        public decimal QD008 { get; set; }
        public decimal QD009 { get; set; }
        public decimal QD011 { get; set; }
        public decimal QD012 { get; set; }
        public decimal QD015 { get; set; }
        public decimal QD019 { get; set; }
        public decimal QD020 { get; set; }
        public decimal QD021 { get; set; }
        public decimal QD022 { get; set; }
        public decimal QD023 { get; set; }
        public decimal QD024 { get; set; }
        public decimal QD025 { get; set; }
        public decimal QD026 { get; set; }
        public decimal QD027 { get; set; }
        public decimal QD028 { get; set; }
        public decimal GE001 { get; set; }
        public decimal GE002 { get; set; }
        public decimal GE003 { get; set; }
        public decimal GE008 { get; set; }
        public decimal GE009 { get; set; }
        public decimal GE010 { get; set; }
        public decimal GE011 { get; set; }
        public decimal GE014 { get; set; }
        public decimal GE015 { get; set; }
        public decimal GE016 { get; set; }
        public decimal GE017 { get; set; }
        public decimal GE018 { get; set; }
        public decimal GE019 { get; set; }
        public decimal GE020 { get; set; }
        public decimal GE030 { get; set; }
    }
}
